source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target :'Weaver' do
  pod 'Texture/Core', :git => 'git@github.com:TextureGroup/Texture.git', :branch => 'master'
  pod 'SocketRocket', :inhibit_warnings => true
end
